### ISSUE TITLE
Ajustar o deploy da aplicação para o branch gh-pages

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cpin/maisfono#12]
Alterar o deploy da aplicação para o branch `gh-pages`. Será preciso modificar o script `deploy.sh` para isto e ajustar configurações no GH.

**Comment by juniorpires** [comment]
@fabriciofx deploy já ajustado.

**Comment by fabriciofx** [comment]
Closed by commit c40163710145e911595143d7887416bba4c276e3
