### ISSUE TITLE
Corrigir bugs referentes as mensagens de erro que aparecem no console do navegador

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#15]
Ao acessar a aplicação pode-se observar mensagens de erro no console do navegador. Suspeito que seja devido a erro de carregamento de algumas bibliotecas. 
Deve-se verificar se essas bibliotecas estão sendo utilizadas. Se não, removê-las do projeto, caso contrário, identificar os erros e corrigi-los.

**Comment by juniorpires** [comment]
Os seguintes erros ainda permanecem: 

Failed to load resource: the server responded with a status of 404 (Not Found)
rt-icons-2.ttf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
socicon.woff:1 Failed to load resource: the server responded with a status of 404 (Not Found)
fontawesome-webfont.woff:1 Failed to load resource: the server responded with a status of 404 (Not Found)
rt-icons-2.woff:1 Failed to load resource: the server responded with a status of 404 (Not Found)
socicon.woff2:1 Failed to load resource: the server responded with a status of 404 (Not Found)
fontawesome-webfont.ttf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
socicon.ttf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
core.js:1449 ERROR a
defaultErrorLogger @ core.js:1449
cb=gapi.loaded_0:236 Uncaught uO
continents.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by fabriciofx** [comment]
@juniorpires A solução foi comentar estas autenticações? Por quê? Elas não deveriam existir?

**Comment by fabriciofx** [comment]
@juniorpires Se elas são desnecessárias, você pode removê-las ao invés de comentá-las. Se for preciso recolocá-las, você pode fazer um revert do commit.
