### ISSUE TITLE
Analisar método de autenticação utilizado

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#16]
Hoje é utilizado autenticação com a conta do Google, porém os dados desses usuários não são persistidos no Firebase.
Talvez fosse o caso de utilizar os métodos de autenticação que o firebase disponibiliza.

**Comment by fabriciofx** [comment]
@juniorpires Precisa mesmo persistir estes dados? Que dados são estes?

**Comment by fabriciofx** [comment]
@juniorpires Certo. Mas tem que ter cuidado ao armazenar dados sensíveis tanto dos pacientes quanto dos fonoaudiólogos. Você já viu se irá ter algum dado sensível, como algum tipo de doença que acometa algum paciente?

**Comment by juniorpires** [comment]
Do paciente terão as deficiências que ele possui e a sua evolução no tratamento. E tanto do paciente quanto do fono será pedido o cpf. Acredito que esses sejam os dados mais sensíveis.

**Comment by juniorpires** [comment]
Artigo sobre autenticação com o firestore:

https://angularfirebase.com/lessons/google-user-auth-with-firestore-custom-data/
