### ISSUE TITLE
Definir solução de controle de acesso

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#17]
Precisamos definir como será a solução de controle de acesso do usuário para podermos dividir qual parte do sistema cada tipo de usuário irá ver/acessar.
Essa issue está relacionada com a issue #16 uma vez que precisamos ter o sistema de autenticação finalizado para definir tipos de usuário, acesso, etc.

No tópico 10 do seguinte [artigo](http://kazale.com/curso-angular-2-aula-9-rotas-e-navegacao/#s10) ele explica o controle de acesso seguindo um padrão chamado Guard. Poderia ser um ponto de partida ou poderemos utilizar outra abordagem sugerida.

**Comment by juniorpires** [comment]
Artigo sobre autenticação com o firestore:

https://angularfirebase.com/lessons/google-user-auth-with-firestore-custom-data/

**Comment by juniorpires** [comment]
Artigo sobre controle de acesso com o firestore:

https://angularfirebase.com/lessons/role-based-authorization-with-firestore-nosql-and-angular-5/

**Comment by juniorpires** [comment]
Estou pensando em definir três papeis de acesso: Fono, Paciente e Admin e criar um componente Menu que exibe o menu baseado nos papéis que o usuário possui. O que acham?

**Comment by fabriciofx** [comment]
@juniorpires Acho uma boa, mas acredito que vá precisar abrir uma outra issue para isso.

**Comment by juniorpires** [comment]
@fabriciofx , @VictorCardoso22  e @Wylianne, a nossa solução de controle de acesso será com o Guard mesmo?

**Comment by fabriciofx** [comment]
@juniorpires Sim, pode usar o Guard. Go ahead!
