### ISSUE TITLE
Remover a seção "identifique-se"  do  cadastro de fonoaudiologo

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#18]
No formulário de cadastro do fonoaudiólogo existe uma seção chamada "identifique-se" onde se escolhe em um dropdown "paciente" ou "fonoaudiologo", porém como o cadastro já é de fonoaudiologo não é necessário essa escolha.

**Comment by fabriciofx** [comment]
@juniorpires Também acho que não precisa dessa identificação. A pessoa já informa no cadastro. Ao se logar, o sistema deveria ser capaz de já identificar qual o perfil do usuário e agir de acordo com este perfil.
