### ISSUE TITLE
Controle de acesso baseado em papéis

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#22]
Como referenciei na issue #17, encontrei como alternativa de controle de acesso o Guard que é do próprio angular. Sugiro que utilizemos ele com a ideia controle de acesso baseado em papéis.
Pensei em criarmos 3 papéis: 

- admin: acesso a área administrativa do sistema;
- fono: acesso as funcionalidades de fono: ver pacientes, fazer consultas, etc.
- paciente: acesso as funcionalidades de paciente: ver fonoaudiologos, sua agenda, etc.

O que acham? 
Se concordarem com essa ideia de papéis estes 3 já suprem as nossas necessidades?

**Comment by fabriciofx** [comment]
@juniorpires Concordo. Acredito que estes três papéis sejam suficientes por enquanto. Mas uma pergunta: se for preciso criar um novo papel é muito complicado?

**Comment by fabriciofx** [comment]
@juniorpires Certo. Então faça estas três primeiro. *Se* precisar de outra no futuro, a gente vê como faz.

**Comment by juniorpires** [comment]
@juniorpires certo.
