### ISSUE TITLE
A página principal "trava" por uns 2 segundos

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cpin/maisfono#27]
Ao tentar abrir a página principal (maisfono.com), ela dá uma "travada" e depois aparece. Isso é ruim, pois dá a impressão que o site não carregou ou que deu algum problema. Acredito que seja porque deve estar havendo algum carregamento de algum arquivo em background e com isso bloqueia o carregamento restante da página.

**Comment by juniorpires** [comment]
@fabriciofx Não sei se é isso mas o angular quando é acessado pela primeira vez ele baixa todo o sistema para o browser. Desse modo o carregamento inicial demora um pouco mas depois fica fluido porque está tudo lá.

Porém não sei se é isso o real motivo dessa demora. Precisa de mais investigação.

**Comment by juniorpires** [comment]
@fabriciofx tu pode verificar se esse problema ainda existe? Porque se não essa issue já pode ser fechada.

**Comment by juniorpires** [comment]
@fabriciofx tu pode verificar se esse problema ainda existe, por favor? Porque se não essa issue já pode ser fechada.

**Comment by fabriciofx** [comment]
@juniorpires Está funcionando corretamente. Vou fechar a issue.
