### ISSUE TITLE
Copyright to template (possível plágio?)

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cpin/maisfono#30]
Verificar se o template que está sendo utilizado na página principal (maisfono.com) possui copyright ou não. Se possui, deve ser trocado. Caso não seja, o trabalho será considerado plágio.

**Comment by fabriciofx** [comment]
@Wylianne Algum comentário?

**Comment by VictorCardoso22** [comment]
Bom dia, eu me disponibilizo para resolver esse problema.
Caso ninguém contrarie, posso iniciar a criação de uma pagina.
O que acham?

**Comment by fabriciofx** [comment]
@VictorCardoso22 precisamos ver se @Wylianne já não começou algo neste sentido. O que você acha @Wylianne?

**Comment by VictorCardoso22** [comment]
@fabriciofx foi isso que pensei, fico no aguardo.

**Comment by fabriciofx** [comment]
@Wylianne Algum comentário?

**Comment by Wylianne** [comment]
@VictorCardoso22 não iniciei, pode iniciar
