### ISSUE TITLE
Mudança de tecnologia de banco de dados

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#33]
Recentemente @⁨Willyane⁩  estava conversando conosco sobre algumas limitações que ela encontrou no Firebase. Para consultas mais complexas tem que se escrever muito além de não poder se utilizar um where com order by, por exemplo.
Foi sugerido então a mudança para uma abordagem tradicional SQL. 
Em um primeiro momento essa mudança custaria tempo, em contrapartida consultas mais complexas e relacionamentos seriam mais facilmente implementados pelo domínio maior do SQL.

O que vocês acham? A longo prazo poderia tornar o desenvolvimento mais fluido por diminuir os entraves encontrados com o firebase, por outro lado temos o custo de reimplementação.

P.S.: nossa modelagem inicial do banco foi feita baseada em bd relacional.

**Comment by fabriciofx** [comment]
@juniorpires @Wylianne Conforme eu disse antes, deem uma olhada aqui: https://github.com/angular/angularfire2/blob/master/docs/rtdb/querying-lists.md e vejam se resolve o problema.

**Comment by fabriciofx** [comment]
@juniorpires @Wylianne Chegaram a alguma conclusão?

**Comment by juniorpires** [comment]
Pelo commit db87eb78406c8d594889cae580f514b26c551339 @Wylianne  deve ter decidido por usar Mysql e PHP.
Alguma  observação quanto ao que precisamos mudar no código do angular @Wylianne ? Pode ser aproveitado parte do código dos services ou tem que se mudar muita coisa?

**Comment by juniorpires** [comment]
De acordo com o que foi discutido aqui e na issue #41  a tecnologia de persistência utilizada será PHP com o framework Slim e Mysql.
