### ISSUE TITLE
Escolha da tecnologia de videochamada

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#34]
Hoje para a videochamada utilizamos o Hangout, porém é um serviço que a google não dará mais continuidade além de que na nossa solução a videochamada é aberta em outra tela não sendo integrada ao nosso sistema.
Como a funcionalidade principal do nosso sistema é a videochamada é importante uma solução integrada para que possamos ter controle sobre ela.

Assim sugiro que procuremos outra solução ou a do hangout, sendo integrada a tela do sistema.

**Comment by juniorpires** [comment]
Encontrei um artigo que mostra como desenvolver uma videochamada com Angular 6 e o serviço Agora.
Esse serviço disponibiliza 10 000 minutos gratuitos por mês o que acredito ser suficiente para a nossa realidade atual.

https://medium.com/@Anderson7301/building-a-video-chat-app-with-agora-and-angular-6-858d72b6fa0d

**Comment by fabriciofx** [comment]
@juniorpires Vi o artigo e achei bacana. Faz sentido. Minha recomendação é a seguinte:

1. Criar uma interface (de OO, não de UI) que represente como se fazer a chamada
2. Criar uma classe que implemente essa interface e esta classe, é que faz a chamada via Agora

A ideia é criar uma abstração e se precisar mudar pra outro serviço, XYZ, a mudança seria apenas para criar uma nova classe XYZ que utilize o novo serviço.

Faz sentido? O que achas da ideia?

**Comment by juniorpires** [comment]
Faz sim. Interessante a ideia.
Vou testar hoje o funcionamento da proposta do tutorial. Caso funcione ok começo a desenvolver a interface.
Entre hoje e amanhã dou um retorno do resultado desse teste.

**Comment by fabriciofx** [comment]
@juniorpires Ótimo! Nos deixe informados a respeito do progresso!

**Comment by fabriciofx** [comment]
@juniorpires Pergunta: esse serviço salva a videochamada? Talvez fosse um recurso interessante salvar as videochamadas, para ter um histórico do desenvolvimento do paciente ou algo do gênero. O que achas?

**Comment by juniorpires** [comment]
@fabriciofx não vi ainda se salva. Mas caso não consigamos salvar temos uma área do sistema onde é registrado pelo fono a evolução do paciente.

**Comment by juniorpires** [comment]
Segui o tutorial porém está dando um erro na biblioteca. Fui no repositório do git dela e lá tem uma issue justamente sobre isso onde duas pessoas estão com esse mesmo problema.

O desenvolvedor perguntou ao cara que postou a issue se ele não teria nenhum demo com o erro para postar no github. Vou tentar fazer isso para ver se ele dá algum retorno.

**Comment by juniorpires** [comment]
Implementei em um projeto novo e funcionou. Talvez nosso projeto tenha alguma dependência que faz com que a biblioteca agora-rtc não funcione.

**Comment by juniorpires** [comment]
Funcionou. Atualizei o angular para a versão 6, o typescript para a versão 2.7.2, o core-js para a  2.5.4 e algumas outras que acho que não teve relação.
Uma(s) dessas dependências estava(m) causando o erro.

**Comment by fabriciofx** [comment]
@juniorpires Acho que ficou tudo ok. Você acha que pode fechar essa issue?

**Comment by juniorpires** [comment]
Acredito que essa biblioteca com o serviço Agora atende as nossas necessidades.
