### ISSUE TITLE
Nova rotina de deployment

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cpin/maisfono#41]
Conversando com @Wylianne entendi que parte do sistema será executado em PHP + MySQL e outra parte em Angular (frontend + algumas coisas de backend?). De qualquer forma, é preciso criar uma forma automatizada de realizar o deployment da aplicação. Talvez um shell script ou algo do gênero. A ideia é que a parte PHP + MySQL execute em um servidor pago que a @Wylianne tem acesso e a parte frontend (Angular) fique no GitHub Pages mesmo. IMHO, eu não sei se gosto muito desta abordagem de separar as coisas. O que vocês acham? @juniorpires @Wylianne @VictorCardoso22

**Comment by juniorpires** [comment]
Como vantagens da abordagem PHP+MYSQL posso destacar:

 - Familiaridade dos membros da equipe com essas tecnologias;
 - Desenvolvimento de queries sem as limitações que o firestore apresenta: 
   https://firebase.google.com/docs/firestore/query-data/queries?hl=pt-br

Como desvantagem existe a reimplementação do sistema de autenticação.

**Comment by juniorpires** [comment]
Quanto ao deploy poderia-se usar o Travis com um script semelhante ao usado no projeto em angular.

**Comment by fabriciofx** [comment]
@juniorpires Concordo que há mais vantagens do que desvantagens na abordagem do PHP+MYSQL. E sobre o script, podes submeter um PR?

**Comment by juniorpires** [comment]
Boa noite, pessoal
Hoje tentei desenvolver a rotina de deploy com o Travis para o projeto PHP.
Tive alguns progressos mas estou com problema para ele gerar o vendor

Além disso quando tento acessar o index do projeto dá erro 500
E tenho um outro projeto com o mesmo framework que funciona
Daí tô sem saber o porquê disso

**Comment by juniorpires** [comment]
O script que estou usando é esse: [.travis.yml](https://github.com/juniorpires/maisfono-rest/blob/master/.travis.yml)

**Comment by fabriciofx** [comment]
@juniorpires Parabéns por ter conseguido! 😄 

Respondendo as suas perguntas:

1. Pelo que eu havia entendido (me corrija se estiver enganado) parte do projeto ia ficar hospedado em um servidor PHP (que pode ser o seu ou da @Wylianne) e parte ia continuar hospedado no GitHub Pages (no caso, o frontend em Angular). É isso ou eu me enganei em algo?
2. @Wylianne o que você acha? Há algum problema de se ficar no servidor do @juniorpires ?

**Comment by VictorCardoso22** [comment]
Acho que seria melhor que tudo ficasse em um único repositório.

**Comment by juniorpires** [comment]
É isso mesmo @fabriciofx . Falo do repositorio git que vai ficar o projeto PHP. Hoje o projeto PHP está dentro do projeto angular aqui no ifpe-cpin/maisfono.

Também pensei nessa questão @VictorCardoso22 . O bom dos  dois projetos estarem no mesmo repositório é que fica centralizado, porém não fica confuso ter dois projetos e ainda de tecnologias diferentes em um mesmo repositório GIT?
Toda vez que um dos códigos for atualizado no git, duas rotinas de deploy serão disparadas: a do angular e a do PHP.

**Comment by fabriciofx** [comment]
@juniorpires @VictorCardoso22 

Ah, entendi. Não tem problema de ficar no mesmo lugar. Não tem problema de você ter tecnologias diferentes no mesmo repositório. Pelo contrário, é até comum. O PHP é o backend e o Angular é o frontend. O que você deve estar estranhando é o processo de deploy, pois *normalmente* fica tudo sob o mesmo servidor web, tanto o código PHP quanto Angular, mas tb não há problema de ficar separado. Aliás, isso também é bastante normal, vide que grandes sites espalham o conteúdo em uma CDN (imagens, JS, etc).
Mas, como eu disse, sou a favor do ficar *mais fácil* para vocês.

**Comment by juniorpires** [comment]
Tranquilo. Achei estranho administrar dois projetos em um mesmo repositório.
Vou então adaptar o script do travis para fazer o deploy dos dois projetos de uma vez.

**Comment by fabriciofx** [comment]
@juniorpires Ok!

**Comment by juniorpires** [comment]
Nova rotina finalizada.
Agora, a cada submissão ao master são feitos os deploys para os dois servidores: ghpages (Angular) e para o servidor PHP (http://jrpires.com/mais-fono-rest/public).


**Observações sobre o deploy PHP:**

A chave ssh pode ser gerada seguindo essa postagem: https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md

**Importante:**  

- Atualmente a geração dessa chave encriptada não funciona no Windows (mesmo o texto mostrando que sim);

- No Linux tive problemas ao instalar o Travis porque ele não aceita por IPV6. Tive que desabilitar: https://support.purevpn.com/how-to-disable-ipv6-linuxubuntu

**Comment by juniorpires** [comment]
@fabriciofx acredito que essa issue já possa ser fechada. O que achas?

**Comment by fabriciofx** [comment]
@juniorpires Concordo. Vou fechar.
