### ISSUE TITLE
Criar uma interface para cada serviço de acesso a persistência de dados

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#43]
Criando uma interface para cada serviço de persistência fica mais flexível a troca de tecnologia de persistência. Uma vez que para isso basta que o código que implementamos a nova tecnologia implemente a interface criada.

**Comment by fabriciofx** [comment]
Concordo. Go ahead!

**Comment by juniorpires** [comment]
Finalizada pelo commit e32985ac35664cfce507f8bf466cd9d2ef39550b.
