### ISSUE TITLE
Padronizar as urls da API para o modelo REST

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#49]
Adequar a API ao formato recomendado de APIs REST.

Algumas orientações podem ser encontradas [aqui](http://blog.caelum.com.br/rest-principios-e-boas-praticas/) e [aqui](https://medium.com/clebertech/o-guia-definitivo-para-constru%C3%A7%C3%A3o-de-apis-rest-470d0c885fe1).

**Comment by fabriciofx** [comment]
@juniorpires Ótimo!
@VictorCardoso22 você pode cuidar dessa issue?
