### ISSUE TITLE
Visual do sistema desconfigurado

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#52]
O visual do sistema se encontra com alguns problemas: 

- Barras superiores desalinhadas;

- Tabelas com dimensionamento incorreto;

- etc.

Talvez devido a alguma coisa no css do tema (como já conversamos e foi levantada essa suspeita).

**Comment by juniorpires** [comment]
Pode-se haver uma relação disso com o problema da issue #50.

**Comment by Wylianne** [comment]
Problema solucionado no commit 81a7e01
