### ISSUE TITLE
Cannot read property 'step' of undefined

### ISSUE THREAD

**Issue by juniorpires** [ifpe-cpin/maisfono#54]
Ao acessar o menu aparece o seguinte erro: 

![erro fono](https://user-images.githubusercontent.com/1533507/51036368-a8e92580-158b-11e9-9675-1de05391e668.png)

Erro encontrado a partir do commit c90a89a2c219f927381a8bc5c805f85823c340d9 (Atualização na Agenda)

**Comment by juniorpires** [comment]
Pelo que pesquisei o erro pode estar no jquery utilizado ser o slim, que seria uma versão com a ausência de muitas funcionalidades.
E pelo que dá para ver a origem dele pode ser o jquery-ui.

**Comment by fabriciofx** [comment]
@juniorpires Se eu não me engano, tem como você montar um jquery "custom", dizendo os módulos do jquery que você quer. Aí ele gera um jquery seguindo estas especificações. No mais, um jquery full é muito grande? Se não for, mete um mesmo e seja feliz! Desempenho não é o foco no momento...

**Comment by juniorpires** [comment]
O problema é que pelo que percebo esse jquery slim é usado pela biblioteca jqueryui então não tenho acesso direto a ele.
Uma opção seria removê-lo mas ele é usado pelo tema. 
@Wylianne , é possível remover essa biblioteca e colocar outra no lugar? Por causa desse erro os links do menu não funcionam.
